---
title: "My Eating Disorder and Science"
date: 2022-06-01
tags:  thinking, life
---

I wrote this as catharsis for myself. 

WARNING: These are my personal and unique experiences. There is discussion of behaviour related to eating disorders. I was diagnosed with https://www.mayoclinic.org/diseases-conditions/anorexia-nervosa/symptoms-causes/syc-20353591[Anorexia (an-o-REK-see-uh) nervosa] and frequently abused exercise. If you're struggling with anything I've discussed, or will discuss, please reach out or seek professional help. I can sympathize but I cannot provide not medical help.


== Why Do I Study Science? 
I was asked to describe "What is Chemistry?". I would describe Chemistry as the
study of the world through the lens of electrons and the elements. When you can
no longer explain something with the elements, then you've ventured off into
another field. For instance, when the system of study becomes too large, such
as studying the behavior of a eukaryotic cell, then you're in the field of
biology. If the system of study becomes too small, such that using the elements
doesn't make sense, like trying to explain the presence of quarks, you've
ventured into physics. Why do I like Chemistry? I think it's the perfect level
of abstraction to observe the world. Chemistry is more than just viewing the
world though. Chemistry explained many of the things in the world that I was
interested in and cared about. One of those things, better described as a
lifelong event, is my recovery from anorexia nervosa. Chemistry helped me open
my eyes to what I was doing to myself. 

== Who am I?
So, who am I? In answering this question I think back to my youth. Perhaps to
forget the world around me (I had a lonely childhood) I would read chemistry
textbooks that my dad bought for me. I drew the entire periodic table by hand
when I was 12 or 13, and hung it on my wall. That was the start of my lifelong
journey into the beautiful world of chemistry. It was also when I developed an
eating disorder.

I'd like to think that I'm a scientist, or at least I believe that I think like
one. Not many people know how I recovered from my eating
disorder. Reflecting, I now see that I used myself as an experiment; an experiment that either resulted in my recovery or something even worse than my starting state. 

=== An Aside
Asian culture doesn't always recognize one's mental illness as a legitimate
illness out of one's control. I had an eating disorder, which is a mental
illness. Because of the stigma of mental illness and the "desirable" appearance
of my physical body, my family and friends could not understand what I was
going through. At some moments I'd be receiving compliments for my appearance,
at other times I would end up screaming fights with my parents about some new
food I had decided to stop eating. If someone you know has an eating disorder,
*do not* tell them how you view them. Frankly, their own ideal "vision" of
themselves has taken hold, and whatever you say could reinforce that dangerous
ideal. I couldn't see any value or worth in myself if I wasn't skinny. Saying
things like "but you're already skinny, you have nothing to worry about"
creates fear because now I'm thinking "but what if I wasn't skinny? What would
you think of me then?". In the end, someone recovers they have to come to that
decision themselves, whatever that reason might be.

I attribute my recovery to science, specifically nutritional sciences. Having a
strong background in chemistry, and a small but persistent flame to recover, I
quickly dove deep into learning about how my eating the disorder was affecting
my body. However, it wasn't like I suddenly decided to do this. I had lost my
period for several months and my hair fell out every time I scratched my head.
I developed stomach issues and my bones would hurt.  I began to become aware of
the state I was in. Using chemistry also allowed me to view food as mere
molecules that my body relied on for functioning, rather than something that
"would make me fat". 

Since I didn't have a personal computer, I read books from libraries. Every
weekend my mom and I would go to the library, and I'd borrow a tall stack of
books spanning topics from nutrition to reproductive health. I was also a cross
country runner at the time, and I slowly began to
take my nutritional health more and more seriously as I become a more serious
athlete (representing my school at competitions). I essentially nursed myself
back to health with the knowledge of science. 

While I had a scientific understanding of how my eating disorder was wrecking
my body, the "mental" part of the eating disorder was still present. My logical
side was constantly fighting with my emotional side. Even though I was eating
more and at a healthier weight, my eating habits weren't healthy. Once a week,
I'd succumb to emotional urges that resulted in me binging thousands of
calories. To offset the calories, I'd starve the day after. For most of my
years in high school, I was stuck in this binge and starve cycle. I had also
found a new sport, bodybuilding. From the ages of 12 to 20, I flirted with many
types of diets and eating styles, like veganism, paleo, IIFYM, fasting, and
more. They were all attempts at my continual restriction of food. 

I knew binging was bad. I knew starving myself was bad. But why then? High
school was one of the most stressful times of my life. Food was the only thing
I could control, or lose control over. My days usually started at 5 AM and
ended at midnight. The pressures of life were getting to me and I expressed my
feelings over food. I was crushed by the IB program, lifted weights for up to 2
hours a day, and was in a toxic relationship. 

This was a dark time in my life. I'm sure you know this feeling and may have
experienced it yourself, but when you look your best to others, you're really
feeling your worst. High school was that moment for me.

In university, I started to develop much healthier eating habits. One of the
reasons I maintained a much better relationship with food is that I learned a
lot about the biochemical mechanisms of how energy is used and stored in the
body through biochemistry courses. Another reason is that I've surrounded
myself with people who can see when I'm feeling unsure about my body and allow
me to vent and express my feelings.

Many life events have caused me to relapse. But what's important, I
think, is the severity of the relapse and my ability to pick myself up. I don't
think my eating disorder will ever "heal". It's just gotten to a point where it
doesn't control my life like it used to. And that's what I strive for every
day. Science is ever-changing, just like my body.


