---
title: "Alberta's New Curriculum: Computer Science"
tags: computer science education
---

I read the new https://curriculum.learnalberta.ca/curriculum/en/c/scik[K-6 curriculum] so you don't have to!

> Computer Science: Problem solving and scientific inquiry are developed through the knowledgeable application of creativity, design, and computational thinking.

== K - 1
> What are instructions? How can we follow and create instructions?

* understanding, exploring and creating instructions
* how instructions influence outcomes and actions
* ordering instructions to create desired outcome
* following instructions is safe; not following instructions during science investigation can be dangerous

== 2
> How can creativity be used to ensure that instructions lead to the desired outcome?

* create and follow instructions
* use of creativity when designing instructions to find desired outcome
* instructions must be created using precision to get desired outcome
* reliability and efficiency: meaning of these two terms in relation to instructions
** these two terms can be affected by how instructions communiated (verbal, visual, etc)
* daily activies have repeating steps; instructions can be simplified with repeating steps
* debugging: learn that this is the process of removing bugs in set of instructions => instructions may not always achieve desired outcome
* discuss advantage of collaboration when creativly solving problems

== 3
> To what extent is creativity related to contributions in science?

* creativity and computational thinking
** breaking task down
** finding patterns
** identifying important details when reading/solving problem
* computational thinking involves creativity
* computational thinking makes it more efficient for humans to communicate with computers
* same outcome can be achieved through different ways => divergent thinking => creativity 
* creativity is important in CS, technology, engineering

== 4
> How can design resolve a problem?

* the design process => structured process of creating something that can be used to meet needs
** consider variety of criteria
* algorithm: sequence of instructions
* artifact: objects/products made by computer, humans, machine, through process of design

== 5
> In what ways can design be used to help achieve desired outcomes or purposes?

* computional artifact
* code is language understand by computers and run on computers _slightly simplified_
* computer can't think for itself, needs code
* code can be block based, simple/complex
* design is translating algorithm into language understoof by computer
* predict what block(s) of code will do when run
* relate block of code to outcome of behaviour
* translate given algorithm to BB code
* loop
* factors involved in design: function, usability, reliability, efficiency
* iterative process of design => build, test, enhance, refine, repeat
* design changes to make design safer or better meet goals => medical devices, cars, phones, computers
* design can be improved through collaboration

== 6
> In what ways are abstraction, design, and coding related?

* abstraction: reducing, filtering, removing unnecessary information
** generalizing patterns, determining what is important to keep, removing unnecessary details
* abstraction in design of coding to make problems/systems easer to think about
* abstraction in daily life: simplified version of something complex
* computational artifacts designed to address societal needs and wants
* coding structures: sequence, conditionals, loops
* abstraction applied in coding to filter out unnecessary information
* previse language/grammer required in coding
* numeracy skills applied in coding include sequencing and recognizing patterns
* computing can have negative impacts that are unintentioanl or intentional
** personal, social, environmental, economic
** computers, coding, technology can have negative or positive impacts

