---
title: "Git, GitHub, Gluework"
tags: technical
date: 2023-12-10
---

Notes for the workshop I'll be giving UBC iGEM.

= Git, GitHub, Gluework


== Slide 1 and 2: workshop schedule and intro (1 min)

1. glue
2. git and github
3. internal documentation

Hello, I'm Lucy, a 5th year combined major in Computer Science and Chemistry! I really like dark chocolate and stews.

== Slide 2: gluework (5 mins) 

So I've put up a picture of liquid glue. Glue holds things together, so that's you can expect glue work to be. The type of work that holds a team together, ensures a team can work together, and more. Without glue work a team falls apart. You have all experienced this many times in school based group projects. One type of glue work is assigning tasks; if no one assigns tasks then one person may end up doing all the work or multiple people all work on the project without coordination, ending up with some work being duplicated.

Glue work is broadly defined as the work required to keep a team functional. Processes like agile, our master tracker and the internal documentation are ways to keep a team on track, transparent with each other. So who does glue work? Everyone in a team should be doing glue work. Those in managerial positions will end up doing more glue work, like assigning tasks or writing out a roadmap, but everyone will be expected to record their weekly tasks and contribute to the internal documentation. Glue work is not a single team or a single person's burden to carry. It is everyone's responsibility.

Updating the internal wiki with what you have done or are planning to do is glue work. A team without documentation is just a bunch of headless chickens running around. The larger a team gets, the more of a necessity documentation becomes. A popular misconception is that the more people in a team, the more work you can get done. That can be true, but is not a given. According to Brooke's law, which is an observation about software project management, we can say that:

1. it takes time for new people to become productive. Many new members here are learning about synthetic biology for the first time. You will have to spend energy to learn about iGEM, whereas experienced members have already done that. Furthermore, experienced members will have to educate and guide new members, because new members are also more likely to make mistakes. Having experienced members document will help new members who will read this documentation.
2. as more people join a team, communication overhead increases. In a team of 3 people, you can easily get on a Zoom call and have a conversation where everyone is on the same page. In our team of 20 people, it's very for people of different subteams to get lost when listening to other subteams. Documentation serves as a way to keep everyone on the same page.

That means everyone must put in the work to be an engaged and active member of our team, one of those tasks being contributing to our internal wiki. If at anytime you feel like something feels wrong or have a suggestion to better engage everyone please let your lead and co-directors know!

== Slide 3: git vs github (10 mins) 

Firstly, what is Git? Git is a version control system that tracks changes in a set of files. Another type of version control is Google Doc's "Revisions". The major different with Git and other version control system's like Google Doc's is that you control when you want to track changes. Google Doc saves every time you make a change to your document, but Git only tracks changes when you explicitly say to. Additionally, Git makes working with many people very easy. When you're working on Google Doc's and don't want someone to edit your work there's no way to prevent that except to create a copy of the document; Git doesn't have this issue. So let's get into some git commands!

With our internal documentation here are the git commands you'll need to use.

To keep your work separate from others: 

`git branch my-branch`
`git checkout my-branch`
 
To track your work:

1. `git add .` 
2. `git commit -m "message"`


When you work with other people, sometimes you need to use a command called `git pull`. 

Now onto GitHub. What is GitHub? GitHub is a cloud hosting platform. You can use GitHub without using Git, but most people use Git to upload their code to GitHub. This is where you need `git push`. So before we try out these commands let's walk through the internal wiki! We'll be using something called Codespaces.

So let's navigate to the GitHub repo for the internal wiki. Everyone start your Codespace, and while that is booting up I'll give a walkthrough of the internal wiki.

== Slide 4: internal wiki walk through (4 mins) 

*walk thought all the pages*

== Slide 5: interactive (30 mins) 

We are all going to add our names to the attributions table. First, make a branch and follow the commands on this slide. The markup language you will be using is Markdown. If you need any help with that just message the documentation channel. After you add your name, git add, commit and push. You may see something called a merge conflict. You can resolve the conflict with Git but it's easier using the GitHub interface. 

So what's a conflict? When you're working with multiple people, Git does something where it tries to merge two different files together. Usually it succeeds, but sometimes it needs the human's help to resolve the merge conflict for it. When you can't push your code due to a merge conflict, you need to make something called a pull request. In fact, anytime you're committing anything you have to make a pull request. A pull request is a way to let your team members that you would like to add your work to the project. This makes it so that the internal wiki is transparent, and allows leads and other team members to read your writing and offer advice or fix spelling errors. It's also common courtesy. So after you make your pull request, tag the leads and then all you have to do it wait. After your pull request has been approved it will be merged in by a lead and then you're done. You've contributed to the internal wiki! By the time we write the iGEM wiki all of you will have enough experience with Git that the iGEM wiki will be a piece of cake.

Total: 50 mins

Source: 

. https://noidea.dog/glue
. https://locallyoptimistic.com/post/glue-work/
. https://en.wikipedia.org/wiki/Brooks%27s_law