---
title: "Daily Log"
date: 2024-04-02
tags: life
---
:toc:

i am tracking my days again. here are the things left to do.

=== research
* read over papers/u of t implementation
* read over some hein lab papers
* review math 200
* check out cpsc 303/302 online

=== life 
* start tracking stats
* take out trash
* clean floor
* do laundry

=== iGEM
* email jordan?
* email math prof guy
* email dr. condon
* prepare codebase for work
* prepare figma for wiki
* pick wiki framework
* send out drylab feedback form
* set up drylab one on one
* finish primer library

=== chem 211
* review unit 1
* review unit 2
* review unit 5
* review unit 4
* review unit 3

=== chem 412
* reviewing lectures
** lectures 1 - 10
*** reviewing eigenvalue matrix
** lectures 10 - 14
** lectures 14 - 18
*** review point groups
** lectures 18 - 20
*** review point group
** lectures 20 - 24
* final (april 16)

== april 16
* [ ] chem 401 finish takehome final
* [ ] chem 211 review/do unit 1 questions
* [ ] clean kitchen
* [ ] clean bedroom

https://web.math.princeton.edu/generals/
https://joaquinbarroso.com/2016/05/26/the-art-of-finding-transition-states-part-1/
https://phas.ubc.ca/~phys304/2008-Phys304Website/
https://phas.ubc.ca/~phys304/2008-Phys304Website/
https://www.sciencedirect.com/topics/chemistry/restricted-open-shell-hartree-fock-calculation
https://onlinelibrary.wiley.com/doi/10.1002/qua.560200502
https://pubs.aip.org/aip/jcp/article/130/20/201101/71039/Symmetry-structured-correlation-in-projected

== april 15
* [*] practice point group stuff
* [*] chem 211 finish ch 12 reading
* [*] chem 211 ps5
* [ ] plan summer workouts
* [ ] chem 211 review unit 1

stuff i want to read

https://faculty.washington.edu/ajko/publications?diversity
https://faculty.washington.edu/ajko/publications?tutorials
https://faculty.washington.edu/ajko/publications?methods


== april 14
* [ ] practice point group stuff
* [*] chem 412 final p1
* [*] chem 401 final
* [*] chem 412 review lectures 20 and more
* [ ] chem 211 finish ch 12 reading
* [ ] chem 211 ps5

i wokeup late because the apartment above me was partying and i couldnt sleep. waking up tired really annoys me and im pretty moody throughout the rest of the day.

== april 13
* [*] filed taxes??
* [*] sent return
* [ ] email about return
* [*] finish ps7
* [ ] finish take home final (412)
* [*] lectures 1 - 10
* [*] lectures 10 - 14
* [*] lectures 14 - 18
* [*] lectures 18 - 20

== april 12
* [ ] finish ps7
* [ ] finish take home final (412)
* [*] finish take home final (401)
* [*] do half of ps5 (211) [done]
* [*] gym
* [*] plan gym workouts

== april 11
* return earring package
* finish ps7

now have everything i need to finish all existing assignments. finished reading divine rivials. not doing a great job being consistent in the gym unfortunately.

== april 8
i need to remember to turn the heat down or i can't fall asleep. i should start tracking calories and workouts more. i didn't realise most of my finals were in the first 2 days. i think i need to eat more protein.

=== workout
* squat
* back extension
* ham extension
* quad extension
* shoulder press
* chest press

=== eaten
* bagel
* coffee
* jam

== april 7
seems like courses have no adjusted for the midterm break. need to make sure i am properly allocating my time, and i need to fix my sleep schedule.

=== workout
* 3 km run
* random stuff

=== eaten
* coffee
* bagel
* two egg
* rice
* bok choy
* egg tart
* pork belly
* beef

== april 6
tired, need to fix sleep.

==== eaten
* 4 dark chocolate, protein pancake
* 1 cup coffee
* bok choy
* tofu
* rice
* pork belly (korean resturant)
* beef (korean resturant)

==== workout
* sumo dl 135 (2*8) 185 (3*6)
* Hp 185 5*15-20
* Cable Lat raise 3*10
* Bicep curl 4*10
* Sl dl to sp 20 4*5

== april 4/5
weight: 120.2

== april 3
i feel kind of resistant to working because i'm kind of stressed and i did not sleep well yesterday. have to wake up and face the sun or something, my eyes are deceased.

== april 2
very tired, need to sleep earlier, because i like to get up early. need to plan out things left to do. i finished the chem 245 lab, finished the characterization problems, didn't do much of the guided inquiry. need to review todays 211 lecture. did some ps6. tomorrow need to do more 245 review, finsih ps6, finish gi discussion questions

=== interesting things
- https://pubs.rsc.org/en/content/articlelanding/2023/cc/d3cc03229a/unauth
- https://pubs.rsc.org/en/content/articlehtml/2023/sc/d2sc05974f
- https://pubs.acs.org/doi/10.1021/acs.orglett.1c04134
- https://pubs.rsc.org/en/content/articlelanding/2022/ob/d2ob00272h
- https://www.thereidlab.com/publications
- https://tanner.chem.ubc.ca/
- https://www.jbc.org/article/S0021-9258(19)78396-3/fulltext
- https://onlinelibrary.wiley.com/doi/epdf/10.1002/anie.199715201
