theme = "no-style-please"
base_url = "https://lhao03.github.io/"
compile_sass = true
build_search_index = true
taxonomies = [
    { name = "tags" },
    { name = "categories" },
    { name = "contexts" },
]

[markdown]
highlight_code = true

[extra]
add_toc = true
header_nav = [
    { name = "~home", url = "/" },
    { name = "#tags", url = "/tags" },
    { name = "+categories", url = "/categories" },
]
footer_nav = [
    { name = "github", url = "https://github.com/lhao03", new_tab=true},
    { name = "gitlab", url = "https://gitlab.com/lhao03", new_tab=true},
    { name = "linkedin", url = "https://www.linkedin.com/in/lucy-hao/", new_tab=true },
]

