name:                lucyWebsite
version:             0.1.0.0
github:              "lhao03/lhao03.github.io"
license:             BSD3
author:              "Lucy H."
copyright:           "2022 Lucy H."

extra-source-files:
- README.adoc

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lhao03/README.adoc>

dependencies:
- base >= 4.7 && < 5
- hakyll
- hakyll-sass
- filepath
- blaze-html
- hashable
- time
- unordered-containers
- pandoc

executables:
  site:
    main:                site.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
