---
title: "Papers and Books and Other Things"
date: 2023-12-24
---

== Books 
2023

* Heir of Fire (reading)
* Crown of Midnight
* Throne of Glass
* House of Sky and Breath
* House of Earth and Blood
* A Court of Silver Flames
* A Court of Wings and Ruin
* A Court of Mist and Fury
* A Court of Thorns and Roses

2022 

* https://criticallyconsciouscomputing.org/[Critically Conscious Computing _Methods for Secondary Education_]
* Your Computer is On Fire 
* Programmed Inequality 

== Paper Ranking

=== Interest
1. I'm falling asleep.
2. Reading through the paper is a like a task and I'd rather read another paper.
3. [TODO]
4. [TODO]
5. The paper is neutral. I don't mind reading it, but I don't think I'd miss reading it.
6. Has some interesting points.
7. [TODO]
8. [TODO]
9. [TODO]
10. I feel excited reading this and would love researching more about this topic.

=== Understanding
1. I don't understand a single sentence.
2. I know less than half of the key words and have a very limited (non existent) understanding of the paper.
3. I know most key words but I can't really understand the main idea of the paper.
4. I know most words and understand the idea but get lost still.
5. I know most key words and have a general idea of the topic of the paper but couldn't explain much about the paper to anyone.
6. I can get a good idea about the topic of the paper, but can't really form any questions or my own thoughts on the paper and I have trouble talking about the paper to someone else and have to refer back. 
7. I can understand the paper and overarching ideas and details well, and have some of my own thoughts on the paper, but those thoughts may be half baked. I can get a general idea of the paper across to someone without needing to refer back the paper.
8. I've come across the same problem/topic in the paper, and understand the ideas and solutions presented, and could talk about them with someone else.
9. I've also thought about the same ideas and come across the same research problem. I can lightly debate about the paper with someone else and can think of questions to ask the authors.
10. I could of written this myself (well not really)! I could probably present the paper to someone else clearly and have a conversation with the authors.

== Papers Read
* CARAT CAKE: replacing paging via compiler/kernel cooperation
* Quantifying SARS-CoV-2 transmission suggests epidemic control with digital contact tracing 
* Dangers of a fixed mindset: implications of self-theories research for computer science education
* The End of Computing Science?
* Guiding Target Synthesis with Statistical Modeling Tools: A Case Study in Organocatalysis
* NonVolatile Memory for Fast Reliable File Systems
* Photodynamic and Contact Killing Polymeric Fabric Coating for Bacteria and SARS-CoV‑2
* ProSE: the architecture and design of a protein discovery engine
* SARS-CoV-2 Evolution: On the Sudden Appearance of the Omicron Variant
* Teaching CS unplugged in the high school (with limited success)
* To Code or Not to Code, That Is the Question
* From Principles to Practice with Class in the First Year
* Understanding and exploiting optimal function inlining
* Geek genes, prior knowledge, stumbling points and learning edge momentum: parts of the one elephant?
* Understanding Sources of Student Struggle in Early Computer Science Courses
* Why Computer Science Doesn't Matter
* Folk Pedagogy and the Geek Gene: Geekiness Quotient
* Developing Behavioral Concepts of Higher-Order Functions
* Every Walk’s a Hit: Making Page Walks Single-Access Cache Hits `[Write up TODO]`
* Fairness and Abstraction in Sociotechnical Systems
* Street-Level Algorithms: A Theory at the Gaps Between Policy and Decisions `[Write up TODO]`
* Glycerol-3-Phosphate Dehydrogenase: The K120 and K204 Side Chains Define an Oxyanion Hole at the Enzyme Active Site `[Write up TODO]`
* Secrets of the Glasgow Haskell Compiler Inliner
** will reread 
** interest: 7, understanding: 6
* How to Enable Index Scheme for Reducing the Writing Cost of DNA Storage on Insertion and Deletion
** interest: 8, understanding: 7.5
* A Programmable Programming Language
** interest: 8, understanding: 8
* Forward build systems, formally
* The Structure and Interpretation of the Computer Science Curriculum
* Finding missed optimizations through the lens of dead code elimination
* A Sociocultural Perspective on Computer Science Capital and its Pedagogical Implications in Computer Science Education
* The development and deployment of formal methods in the UK
* Structural versus Pipeline Composition of Higher-Order Functions (Experience Report)


== Videos Watched
* https://www.youtube.com/watch?v=mkzHIhKaUX4[Learning to Code: Why we Fail, How We Flourish]
* https://www.youtube.com/watch?v=ho7oagHeqNc[Category Theory in Life]
* https://www.janestreet.com/tech-talks/curriculumn-design/[Shriram Krishnamurthi's Talk: Curriculum Design as an Engineering Problem]
* https://www.youtube.com/watch?v=4HgShra-KnY&t=771s[ASPLOS Keynote: The Golden Age of Compiler Design in an Era of HW/SW Co-design by Dr. Chris Lattner]

== Dissertations
* http://www.diva-portal.org/smash/record.jsf?pid=diva2%3A837505&dswid=3179[Feminist Technoscience Strategies]


== Articles I resonated with
* https://www.wired.com/story/the-unwritten-laws-of-physics/[The Unwritten Laws of Physics for Black Women]
