---
title: "💼 My first job: PROOF Centre"
date: 2021-05-21
tags: life
---

Who would have thought that my first job would take place in my bedroom?
Definitely not me. Even less did I think I would end up: 

* writing over 6000 lines of Python 
* being part of a research paper (in the progress of being published to a peer-reviewed journal! Check out the unofficial manuscript: https://www.medrxiv.org/content/10.1101/2021.05.04.21256134v1

But not everything was _great_. I also ended up: 

* sitting for very long hours 
* getting horrible headaches and super dry eyes 
* multitasking (when I really shouldn’t be) 
* feeling unqualified at times

== The great

I was the youngest and only co-op student hired to work at the PROOF
Centre. I was also working under a UBC professor, surgeon, and PROOF’s
chief data officer. So I was feeling pretty nervous the week before I
started working. But as I got more familiar with the team members, I got
less and less nervous. Additionally, my supervisor (PROOF’s chief data
officer) made it super clear that I was here to learn. That’s something
super important I keep reminding myself every day: you’re here to learn
and mistakes are bound to happen.

I won’t lie; when everyone around you has a master’s/PhDs and you’re
just a second-year undergrad student, it can feel intimidating. But when
I made a mistake or was unsure of how to do something, someone was
always there to help me out. Someone was always available and willing to
help me out, whether it be technical issues or more personal issues, and
that’s what made this co-op term so great.

Additionally, I got to attend a bunch of presentations put on by other
PROOF members! Such presentations included topics like SHAP (SHapley
Additive
exPlanations)footnote:[https://shap.readthedocs.io/en/latest/[SHAP
(SHapley Additive exPlanations)]] and biomarker research on diseases
like asthma, allergic rhinitis, and pulmonary exacerbations in cystic
fibrosis (super cool stuff that I barely understood). I’m fortunate to
have the opportunity to listen to such talented individuals and have
learned so much!

== The not so great

My father says that he loves remote work, but I don’t think I can say
the same 😅 (maybe it’s because I haven’t experienced the commute
before). And being a first-time developer and intern, I wished I had
done some things differently. With that being said, some not so great
things I experienced include:

* sitting for long hours
* having the sorest and driest eyes ever
* forgetting to eat meals
* headaches
* feeling alone
* not asking enough questions
* not being clear enough
* working 10 hours one day and 4 hours the next

These are things I’ll be continuously working on improving in future
internships to come! But I wanted to list them because as interns, we
feel like we have to be perfect and not mess up, but the whole point of
being an intern is making mistakes and learning from them!

== Final thoughts

When I had my first call with my supervisor in January I thought to
myself "wow four months". And in a blink of an eye, these 4 months
have passed. I’ve made many connections, learned a lot of things, and
saw the impact of the work I was doing. I’m proud of what I was able to
accomplish over the 4 months and am thankful for the PROOF Centre for
having me as a first-time intern 💖.

