---
title: ranting about stuff
tags: thinking
---

== Longtermism and Effective Altruism

There's a vibe or culture in the technology industry that software engineers or
people in tech are doing God's work. What do I mean? 

++++
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The obsession some in my field of computing have over the existential risks of superintelligence is yet another example of the dangerous philosophy of longtermism.</p>&mdash; Grady Booch (@Grady_Booch) <a href="https://twitter.com/Grady_Booch/status/1530279557604945920?ref_src=twsrc%5Etfw">May 27, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
++++

These religions or philosophies, which I've now learned are longtermism and
effective altruism, encourage and condone people of privilege to throw time and
money at is statistically or "empirically" good. For instance, someone may say the people of the future have more "value" than the people currently alive, and thus direct their time and resources towards solving problems in the future.

One large current problem is climate change. A problem of the "future" is apparently AGI. But longtermism seems to say that: 

"Climate change seems unusually solvable for a global issue: there is a clear
measure of our success (how much greenhouse gas we are emitting), plus lots of
experience seeing what works — so there is clear evidence on how to move ahead.
[...] As a result, while we agree that it’s crucial we work on reducing
existential threats to humanity, and agree that climate change increases those
threats, we usually recommend people interested in safeguarding humanity’s
future focus on bigger and more direct existential threats if they can."
-- https://80000hours.org/problem-profiles/climate-change/

What seems like a clear motive, "how much greenhouse gas we are emitting",
completely tosses aside the ecological damage that will be done to our earth.
Our world doen't act in a pure fusion. It is true that there are many paths to
a final outcome. In physics and mathematics, the path from the initial state to
the final state can be neglected, and thus these types of equations are called
state functions. But in many chemistry concepts, this is not the case; the path
from the initial state to the final state matters, and these types of equations
are path functions. The "measure of success" of climate change, say getting to
below X greenhouse gas emitted, can have many different paths: one that destroys
the ecosystem and people, or one that tries to preserve it (the people most
damaged by climate change are often the ones holding the least amount of
power). And I believe this path is important. Climate change is a path
functions.

Actions set off a chain reaction of other actions. As a chemistry major, I know
this too well (I literally study
chain reactions).

And what worth is space exploration and AGI developed when no one is there to
witness it. Or the real question is, how does one decide that the lives of
people now are worth less than the lives of the
privledgedfootnote:[https://aeon.co/essays/why-longtermism-is-the-worlds-most-dangerous-secular-credo[Against
longtermism]]? 

While longtermism (and effective altruism) are not exclusive to the technology
industry, these views, are expressed in this community. Trendy and hyped up
ideas in the technology industry like AGI and Web3 fall into ideas of
"unlocking human potential" or "building technology to help all", offering a
techno-utopian idea of what the world could be. Myself, and other computer
science students I interact with dream amongst ourselves of building software
solutions to "solve problems in the world". We slap technology on every
problem, telling everyone that "coding is the
future!"footnote:[link:/posts/learn-to-code/#_instant_gratification_and_tech_solutionism].
These were the type of ideas that entranced me into a computer science degree.
It offered everything a chemistry degree couldn't. 

There were so many ways that I tried to justify why I decided to pursue a degree in
computer science. I've eventually realized that my reasons were treading along
the line of longtermism and effective altruism.

I've seen many LinkedIn posts start off with how one wishes contribute to
society positively, or to help people in general. What follows is a job
announcement saying they've accepted a job offer at Facebook/Meta, Snapchat or
some other giant tech company. Which is pretty funny to me; we've seen the
damage Facebook has done via misinformation about vaccines, COVID-19 and the
Holocaust. Facebook does much more harm to society, so who are you trying to
convince when you start off your LinkedIn post saying that you've always wanted
to help other people and then announce your internship at Meta? I know why people accept Meta internships; big
pay, big name and big tech. Who cares about impact? But we all like frame it as
doing good impact. 

== Most of what you're doing is useless
The truth is, most jobs are useless, especially in the tech industry. What gets
accomplished by a few open source developers spread around the world is exponentially more
than an 100+ team of software engineers at a company. Most of the most important, impactful and relied on software has been developed by people who
expect to get paid next to nothingfootnote:[Almost all of the software I use in my day to day life has been due to the contributions of open source development. For instance, Fedora, Ubuntu, Emacs, Vim and all the programming languages I use.].
I used to think software engineering was useful
, but through reading conflated LinkedIn posts and advancing through my
degree, I realized software engineering gives big money for people doing a disproportionally small and "useless" amount of work

On the other hand, researchers in chemistry or microbiology get payed absolute
shitfootnote:[https://www.nature.com/articles/d41586-022-01392-w] for work such
as finding cures for cholera, which doens't affect anyone in
the Western hemisphere, but is a daily cause of someone being unable to work or
care for their family in developing nations.

My internship at Microsoft solidified that view. Microsoft has so many internal
projects that a phrase I've come to think about quite often is that Microsoft
throws shit at the wall and sees what sticks. My internship project was another
"piece of shit" to throw at the wall. I got paid so much money to scroll a few
pages of Redux documentation and then open some trivial PRs. 
I could no longer fool myself. My internship at Microsoft was one of my
breaking points of realizing I couldn't stay in the technology industry.

== Agile 
Oh and don't get me started on agile, sprints, and starting off user stories
with "As a user..", like that's gonna make the user story any more useful. At
Microsoft I spent upwards of 4 hours per week with my team planning these user
stories and listening in meetings with PMs talking about color schemes and
button placements. Instead of improving on old products, most big tech
companies just keep pumping out for shit for some fantastical user. Look at
Windows 11 and Teams for Life. In Windows 11, they introduced 6 preset tiling
options for your applications. But Linux Pop!_OS) does this, and for free. The
Windows 11 release video even said that "No other operating system offered
tiling". Had they took a second to look at Pop!_OS they could have saved
themselves the embarrassment in the Linux subreddit. 
