---
title: Daily Log
tags: life
date: 2022-05-31
---

I used to have a failures page, but I thought, why not just record I feel everyday? I think it gives more insight into my struggles and thoughts.

= May
== May 31: 
ubc does course registration based on your year standing, and i majorly fucked
up in second year by not making sure i was taking enough cs/math courses to be
promoted to third year (i was 0.4 credits away from being promoted to third
year standing). since i was stuck in second year standing, i got a shit
registration time (second year students are the last to register for courses),
so this meant i got "whatever was left" and i couldn't register for literally
any third year CS courses even though the only second year courses i only left
to do were the required second year math courses. i randomly got a seat into
cspc 313 because i kept checking the ssc every like 5 mins and then was one of
the last students to get moved off the waitlist into cpsc 320. and then i saw
like at least 10-20 people drop the third year cs courses i wanted to take but
i couldnt register for since it was past the register date, and i wasn't keen
on joining a course like 3 weeks into it. since i could only register for 2
third year courses i couldn't get promoted to fourth year (this is my fourth
year at ubc but im in third year standing now). and now i have to do a bunch of
course schedule juggling between my chem and cs courses, and one of the cs
courses i was planning to take suddenly changed times and that threw my whole
schedule out of balance and now i'm replanning my next two years again. in
second year i was a super confused student, and i was exploring courses in micb
and chem, instead of taking the required math courses, and i feel like i was
punished for "exploring". i kinda wish i had an advisor (my friend at an ivy
school gets assigned their own advisor and they meet like a few times
throughout the year). anyways i guess i feel stressed, because course planning
is just another thing i have to worry about along with all the stuff happening
in the world.

i also procrastinated something i should have done like one month ago. 
