---
title: "molecules or money? end of third year reflection"
tags: life
date: 2022-05-01
description: After three years in university, I finally switched my major to a combined major in Computer Science and Chemistry. I also dropped all extracurricular activities that no longer aligned with my values and interests. But why has it taken three years? And why did I have so much difficulty in making these changes?
---

_Updated: 2022-05-06_

After three years in university, I finally switched my major to a
combined major in Computer Science and Chemistry. I also dropped all
extracurricular activities that no longer aligned with my values and
interests. But why has it taken three years? And why did I have so much
difficulty in making these changes?

== my values

I think my values about a lot of things have changed since I first
entered university. For instance, my stance on computer
science/technology, what I want to do with my life, and more.

=== my stance on computer science and technology

When I first started university with the intention of majoring in
computer science, I had no idea what computer science was. My high
school wasn’t a tech hotspot and none of my friends were doing computer
science. They were all doing pre-med programs. I sometimes wonder what
would have happened if I did pre-med. I probably would have gone to
UofC. But I didn’t want to do pre-med. I wanted to do chemistry.

Up until my last year of high school, I knew I was going to major in
chemistry. I didn’t think about job prospects or money, mainly because
my parents didn’t talk about jobs that much, and they didn’t let me know
anything about money. My parents didn’t nag me to become a doctor or an
engineer, and any money I earned I just gave to my parents to manage. I
was largely disconnected from the real world until it was time to apply
to universities.

When I was applying for universities, my parents started to bombard me
with information on money, living alone, and jobs. My dad warned me that
it would be hard to get a high-paying job as a chemistry undergraduate.
And suddenly, I became really worried about how I was going to earn
money as an adult. What would I do with a chemistry degree? Can you live
off a chemistry degree? My dad was a real life example that served as
the major reason why I couldn’t pursue chemistry. He studied chemistry
for years, making it into a PhD program. At the same time, I was born.
My father suddenly came to a fork in the road: continue his graduate
studies in chemistry where he was getting a measly graduate student
salary to support his new family or change programs to study computer
science so he could get a job in software and support his family with a
much higher wage. He chose software, and has provided a wonderful and
amazing life for our family. So I also chose to pivot to computer
science. I’m largely influenced by my father. We have similar interests
and similar worldviews. So it was natural for me to also choose to
computer science.

🫠

I chose UBC because of its computer science program, and I’m pretty
happy with the choice three years later. But my first and second years
of university were pretty messy and confusing. As someone who had no
idea what computer science was, I tried to learn about it. I went to
hackathons, learned about the hottest trends, and did side projects. I
was the stereotypical computer science student. I listened to what other
people had to say, about how AI was the solution to all our problems,
which companies paid the most to interns, and what web technologies were
the shiniest. I thought computer science was awesome. AI was amazing,
hackathons gave so much free food and swag and you could build awesome
side projects on your own. Computer science had an easiness to it. It
was easy to love AI because everyone was talking about it. It was easy
to activate your reward centers with the free food and swag at
hackathons. It was easy to think you did something useful with all those
shitty side projects you built.

So that’s how I justified that I liked computer science. The easiness of
it. As a way to justify my choice further, I told myself that
"chemistry didn’t have it this easy". No one would let a bunch of
chemistry students into a lab to concoct up an experiment on a drug
that cures everything. No one gave the chemistry majors free food and
no one told chemistry majors that they were the future.

Of course, I could only fool myself for so long. Firstly, I started to
dislike link:/posts/hackathons[hackathons]. link:/posts/leaving-extrac[I used to organize hackathons] and
stopped this year because of how hackathons clashed with my
values. What made me stop going to and attending hackathons was the
techno-solutionism and techno-utopian hype. As a participant and
organizer, I’d witness an improper use of technology on a large societal
problem. A simple quiz with stock photos of food made with HTML and CSS
that tried to diagnose you with an eating disorder still haunts me
today. I remember going through the quiz and becoming angrier and
angrier at how reductive the questions were. And these were the projects
that were awarded thousands of dollars; trying to replace therapists
with AI-powered mental health apps, trying to replace doctors with
AI-powered web apps and more. Fun games with breathtaking graphics and
immersive storylines never won any awards, no matter how well they were
designed and programmed. I’d rather play a game than have AI decide if I
have an eating disorder. A project that was duct-tapped together with
copy-pasted code from the internet, which claimed more than any
application could ever do, were the projects that were winners at
hackathons. I was so disgusted over how people could just claim their
project solved a problem in the world. How "easy" it seemed to be to
find a technical solution to any problem.

[quote, Lucy Hao, 'link:/posts/hackathons/#_what_are_we_trying_to_solve_here[My thoughts on hackathons]']
____
It’s funny how a microbiology class fundamentally
changed the way I went about thinking about solving problems. In MICB
202, I learned about cholera, an acute diarrhoeal infection caused by
ingesting water or food contaminated with the bacterium Vibrio cholerae.
How would one go about reducing the number of cases of cholera? Well, by
cleaning up the water. But how? Using chemicals? Using energy to kill
off bacteria? While these are solutions, there’s one thing we are
forgetting about: the context of the problem, and those who are actually
affected. The context is that the location (Bangladeshi villages) where
cholera is still an issue is in places where water is used for
everything, usually not being filtered or cleaned before the water is
used. The water that people use to drink is also used for washing. So
you can’t just dump chemicals into the rivers and hope for the best.
Additionally, there’s a lack of resources. Who’s going to synthesize
chemicals and where would you even purify the water? Even boiling water
would be a strain on resources (it would be better to use firewood for
heating or cooking). To someone that is unfamiliar with the context of
the issue, it’s easy to slap a solution together and actually cause more
harm than good.

So what was the solution the researchers came up with? The solution is
quite simple and is a solution that can be easily adopted and pushed out
into the public. It was to use a sari, a piece of cloth worn by Hindu
women, but also now frequently worn by women of other religious groups.
This solution is one I didn’t even think of when my professor presented
the case study in class. Why? Well because I didn’t have a good or even
basic understanding of the context of the problem, such as the cultural
practices.
____

Hackathons had a similarity with the fast-paced nature of Silicon
Valley, grabbing at every trend possible, and awarding money to people
who promised elaborate solutions that eventually fell flat. Hackathons
were easy. Easy to feel like you understood technology and easy to feel
like technology is all good and powerful. Easy to become entranced with
the values and goals of Silicon Valley, jumping on new trends like no
tomorrow with the mentality of "move fast and break things".

In my first year of university, I remember thinking "how am I supped to
keep up with all the trends?". I took some online courses on AI because
that’s what I thought I should do. I also tried to build a "full-stack
project" with MERN or whatever the hottest tech stack was because
that’s what I thought I should do.

At the end of my first year of university, I decided that I was done
with computer science. I started to feel something like this:

[quote, Shana Vu, 'https://newsroom.ucla.edu/stories/cracking-the-code:-why-aren-t-more-women-majoring-in-computer-science[Cracking the code: Why aren’t more women majoring in computer science?]']
____
"If someone stays in the major, it’s usually because
they have strong peer connections," she says. "When they leave, it’s
not because they’re not capable, but it’s typically because they have
this idea that CS does not contribute to the social good, and they want
to help people."
____

I didn’t have many friends, and I didn’t like constantly being confused
about what was hot and what I was supposed to learn. AI? Web Dev? I kept
wondering why I was spending my time learning about things I wasn’t
interested in like web development. Everyone was telling me to learn
vocational skills because school was "too theory based". (I don’t
think the main responsibility of universities is to teach vocational
skills, but complaints of universities "failing" computer science
students by not teaching them technologies like React is one I hear a
lot.). I guess I wasn’t interested in learning vocational skills. But
that was what everyone else in computer science was doing, and I was
doing what everyone else was doing ever since my first year of
university.

The root of the problem was that I didn’t know _anything_ about what
computer science was. I knew chemistry had many subareas like organic
chemistry, analytical chemistry, theoretical chemistry, etc. and I had a
basic understanding of what each of these subareas was about. However, I
didn’t know about any subareas of computer science. I thought computer
science was _only_ AI and web development. I’d complain to my boyfriend
"I don’t wanna do AI or web development" and he’d say "then don’t".
But I didn’t know what else there was in computer science. I had no idea
what you learned in the algorithms and data structures course, the
computer systems course, and basically, every computer science course
offered. I had spent my first two years of university doing what other
computer science majors were doing, which was preparing to getting a job
in big tech. And that’s what I thought was _useful_ for my future: to
get a job in big tech. If lots of people were doing that then it must be
useful? Right?

On the other hand, my boyfriend just learned and studied whatever he
wanted to. He dove into the world of ML languages (and no not machine
learning) like Haskell. He learned about things everyone told him
"wasn’t useful for getting a job at Google/Amazon/BigTech". And he
didn’t care at all. He’s one of my largest motivators and inspirations
and why I said fuck it and registered into organic chemistry one day
before the course drop deadline this year.

=== the tech industry

Hackathons (which I dislike) were my first exposure to the tech
industry, and my internship at Microsoft solidified how much I detested
the tech industry. I was shocked at how much interns got paid for doing
pretty useless work. Yes, the work I did during my internship at
Microsoft was useless too. It didn’t help that I didn’t even like what I
was working on at Microsoft. At my first research job, I used NLP to
quickly extract information from highly structured health documents. My
salary was 3500 CAD a month, with 75% of that subsidized through a
biotechnology grant. My work was intellectually stimulating and I worked
with amazing and passionate people. At Microsoft, my salary was 5000 CAD
a month, my work bored me to my wits, and I had to work with colleagues
who I despised because they didn’t seem to put any effort into the team
project, which would bring the progress of the project to a halt,
blocking the entire team’s ability to work. Interns I worked with at
Microsoft exhibited macho heroics and other tech bro behavior, leaving
me so frustrated on the last day of my internship I decided that no
matter how much I was going to be paid I would not accept my return
offer. My return offer to Microsoft was 7000 (or 7500, can’t remember)
USD a month to their Bellevue campus in Seattle.

There’s a lot money floating around in the tech industry. Tech
billionaires throwing money at technology to solve problems they have no
understanding of. Venture capitalists throwing money at AGI, for reasons
beyond by understanding (maybe it’s because of the idea of
long-termism). In the path to develop AGI and other tech hype things
like Web3, people have been, and are being exploited
(https://www.technologyreview.com/2022/04/20/1050392/ai-industry-appen-scale-data-labels/[AI
exploiting people] and https://web3isgoinggreat.com/[Web3 disasters]).

++++
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">How can we let it be known far &amp; wide that there&#39;s a religion in Silicon Valley (longtermism/effective altruism &amp; similar) that has convinced itself that the best thing to do for &quot;all of humanity&quot; is to throw as much money as possible to the problem of &quot;AGI&quot;...</p>&mdash; Timnit Gebru (@timnitGebru) <a href="https://twitter.com/timnitGebru/status/1520532465474883584?ref_src=twsrc%5Etfw">April 30, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
++++

I became, and still am, largely inspired by folks like
https://twitter.com/timnitGebru[Timnit Gebru],
https://twitter.com/_alialkhatib[Ali Alkhatib],
https://twitter.com/amyjko[Amy J. Ko],
https://twitter.com/emilymbender[Emily M. Bender] and
https://twitter.com/smdiehl[Stephen Diehl], who are doing work to hold
the tech industry accountable.

I really like what Amy J. Ko says in Critically Conscious Computing.

"Society has not yet broadly decided to make
programmers responsible for their code and its impact, and until it
does, making room for algorithmic justice will require personal and
organizational will."
-- Amy J. Ko, https://criticallyconsciouscomputing.org/[Critically Conscious Computing]

Currently, not much personal or organizational will exists, and that
troubles me.

=== learning about what i like

I eventually came to enjoy learning about computer science.
Specifically, the areas of programming languages and systems like
compilers and operating systems. My fascination started when I took CPSC
213 and read Critically Conscious Computing, which enabled me to view programming languages and
operating systems in a different light; both technically and from a
critically conscious point of view. I wouldn’t have thought I’d be
interested in something like an operating system. Why? Well, many
upper-year computer science students said they dreaded every second of
the third year computer hardware and operating systems course so I
believed that I’d have the same experience. But it was quite the
opposite for me, as hardware and operating systems finally clicked with
me, whereas algorithm design and analysis was a course that tested my
limits and made me doubt my abilities.

At the end of my third year, I think the dust has finally settled down.
I no longer try to learn what’s "trending" and I do not touch web
development (I’m not even good at web development). That full-stack app
I mentioned I was going to make never happened, and never will.

== degree dilemmas

Lots of students change their majors. But chemistry wasn’t just
"chemistry" for me. It was the subject area that I, and my dad, are
both still passionate about. The difference is that my dad didn’t get to
pursue his dreams and passions. He had to pivot to the software
industry, which was booming at the time I was about to be born. His
dreams and passions could not support his family. So in a way, it felt
wrong, for me, his daughter, to pursue her dreams and passions, which
were so similar to his. I struggled with these thoughts a lot. I was
also scared that doing a degree in chemistry would lead me to a bleak
future (I felt like I needed to make my parent’s hard work and
sacrifices worth it). I saw how undergraduate chemistry and biology
majors struggled to find a job while computer science majors could
easily get an internship paying five times more than a lab assistant. So
I became a computer science major, but I still wanted to do _something_
that had chemistry. I still wanted to learn about chemistry.

So what did I do? I tried out everything _but_ chemistry. I did courses
in biology, microbiology, and biochemistry. But none of them clicked.
Every time my biology, microbiology, or biochemistry professor mentioned
something about chemistry in relation to a lecture topic, I got so
excited! But it would only be for a few minutes. I soon realized that
the parts of courses I liked the most were the parts in which the
professor made some connection to chemistry.

After encouragement from my boyfriend, I did it. I registered for the
organic chemistry course one day before the drop deadline. Whoever was
managing the chemistry undergraduate advising requests and added me
enrolled me into CHEM 213 changed my life that day. Even though I failed
quizzes, CHEM 213 was like a fresh of breath air for me. I was finally
letting my 18-year-old out: she could learn about chemistry!

Did I get that A+ in organic chemistry? Hell no. After a year of not
doing any chemistry and taking the "biological sciences" route to the
"chemistry" version of organic chemistry. (Essentially, UBC offers
organic chemistry for chemistry majors, biological sciences majors, and
biomedical engineering majors. I took the organic chemistry course for
biological science majors and after getting a good grade, I was
permitted to take the chemistry version of organic chemistry). But my
subpar grade doesn’t bother me that much, since I learned so much. I was
able to read through a paper that a chemistry professor at UBC wrote.
Every time I came across a concept I understood like "Friedel Crafts
Alkylation" or "iminium" I’d excitedly let my boyfriend know that _I
know what that means!_. Last year I would have not been able to do that.

Changing majors isn’t all rainbows and sunshine. Due to my advanced
credit from IB, I could have finished my computer science degree in
three years. Because I did co-op (and then dropped out from co-op),
didn’t plan my courses well, and switched my major, now I have to take
five years. Right now, I think the extra year is worth it.

== what’s next

Currently, I’m listening to a bunch of Dreamcatcher and
reading papers on operating systems,
compilers, programming languages, computer science education, and
chemistry. I’m finally becoming okay with the things I like and worrying
less about doing what others are doing. I take courses that I want to
and finally accepted that I want to learn about chemistry.

Something from my chemistry professor that I think a lot about:

"[…] I opted to make molecules because if I ever gave
that up, I could always make money whereas if I chose the money option,
I would never have a chance to make a molecule."
-- Dr. David Perrin, https://perrin.chem.ubc.ca/about-dr-perrin/[About Dr. Perrin – Personal Profile]

I’ll end this post with the same question my chemistry professor asked
himself as an undergrad, which perhaps is the same question I’m going to
have to answer soon: money or molecules?
