---
title: "do i want to tech?"
tags = industry, criticism, thinking
+++

IMPORTANT: These experiences situated within a  Western (American and Canadian) perspective. These are also my personal and unique experiences. If I offend you, I'm sorry, but you can choose to stop reading at any time. 

This blog post has been many months in the making. I started writing this in March of 2022, and I'm coming back to this post in December. Since I started writing this, I've been autopiloting in life. My chemistry courses proved much harder than I thought they would be, and I had many doubts about whether spending an extra 2 years in school to learn chemistry was worth it. When I think about what I want to do after school, I know what I want to to do; in fact I've known since high school. But after 4 years of doing just computer science, the chemistry fundamentals I thought I had; well, I've forgotten them. It's only human to forget; my father did a PhD in chemistry and doesn't remember how to do all those complex differential equations. So I've been autopiloting, because it's easier than sinking into my thoughts of self doubt of whether I could actually get into a grad school for chemistry or constantly wishing I could go back to the start of university and redo my major. Over these past few months, I feel like a broken record, struggling to memorize all my organic reagents and pKas, then having spiralling thoughts of just feeling like I'm way to behind ever pursue a career in chemistry.

In my almost four years of university, I've interned in the research sector, industry sector, and academia (as
a teaching assistant). From becoming an outsider to an supposed insider, to attending hackathons and completing Andrew Ng's Deep Learning course, to grinding LeetCode and dragging tickets from "To-Do" to "Complete", I've become the typical computer science student, maybe the definition of a "successful" computer science student. I thought the more I learned, the more I'd like software. I thought I could force myself to enjoy coding, to enjoy all that "technical" talk and to enjoy the projects I was assigned to working on. But I just couldn't. Besides my research project, I really thought I was wasting my time and energy in industry/corporate settings. At Microsoft and Capital One, I got paid loads of money to just write code. Maybe that's the dream? But I was miserable most of the time when I worked on these projects. I couldn't care less about the business impact, and I didn't even enjoy writing code that much. I'm coming closer and closer to the conclusion that I don't like being a software engineer. I don't like coding, I'm not interested in networking or systems. I've tried to be interested in operating systems, telling myself, "it's just like how a cell works", but it's really not the same. 

In a discussion with a colleagues at Capital One, one that was studying physics and computer science asked us if we ever had questions like "how do clouds work?" or "how do telephones work?". Some people said no, but I said yes. I liked thinking about why phenomenon worked, how do drugs work, how does hemoglobin work, or how vaccines work. I didn't really care business impacts or serving customers, or writing code. I think those three concepts core to being a software engineer, none of which I really enjoyed. 

== passion
One question I like to ask other interns or computer science students is "why do you study computer science?". Many answer's I received fell into four categories: money, coding since X, failed mathematician/physic, I dislike everything else. One, was that they had been doing something related to computers since they were X years old. Two, was that in it for the money. Three, they liked math or physics, but wanted something more applied. And finally four, they simply didn't like any other major. Rarely did many people say they actually liked computer science. 

I believe that passion in a field, is an important factor; you should be excited about a subtopic in that field. Unfortunately, many people's reasoning for being a computer science major fall into the fourth or the first category, usually falling into the union of these
categories. The people in the union of the two categories or a person in the "I dislike everything else" is a person I hope to never become. There's a moment I remember when I was attending a computer science event for women at my university. I was in the computer science major for money, and I was trying to find other reasons to stay. I asked one person "Why did you choose to study computer science?". Their answer has still stuck with me for 3 years. They told me "They hated every other (science) major.". To a first year student, it wasn't great to hear that computer science was "the major for people who hated every other major". I hope to never be doing something because I just wasn't interested in every other option available.

To be fully transparent, I pursued a computer science degree because I was attracted to the idea of a high salary. My parents were immigrants, and in combination with the guilt I had having lived a privileged life and to pay back my parent's sacrifices, I felt like I couldn't pursue a fruitless degree like chemistry.
p
== rigour

== correctness

== care
Programs are built with shitty ecosystems like consisting of a bunch of slapped
together JavaScript libraries, a messy and unmanageable ecosystem of
developmental tools that don't even work, and people that don't care. 

Comptuer science was also an easy path to a high paying job where people envied you for
the free food and MacBooks. There's so many people who don't really care about
tech, just about getting paid lots of money. Of course, greedy people exist
everywhere, but I see this more common in the technology industry. 

The technology industry is a gold rush. Enrollment in comptuer scince programs have skyrocketed and I'm 100% sure it's because of the promise of glory and gold.

/* - not considering power or memory use (not efficient) */
/* - building quick and fast software */
/* - people over tools (bad) */

== fundamentals
I've had hackathon attendees and students ask me what they should learn, and
100 percent of the time it's in relation to what the hottest web development
technologies are. Recently, I had a student ask about how they could learn more
about Web3. To say I was floored was an understatement. Is this what our world
as come down to? Everyone chasing the "hottest things". Why? I'm no longer one
to "chase the next hottest thing". Agile and the fast paced culture of Silicon
Valley, along with people who don't give a shit about impact means they just
learn what's hot and trendy. I tried to do this in my first year of university;
learning the MERN stack, React, Django, AI and absolutely hated it. What's hot
and trendy doesn't mean it's right and doesn't mean it's any good. Bouncing
around and learning random stuff in hopes of "hitting the jackpot" is against
most of my morals and "life rules". It's like trying a bunch of "hacks" to lose
weight. My eating disorder recovery was a long and gruealing process filled
with emotional and physical work.

As a TA, I struggle with the thought of whether I should be in charge of
"giving a student advice" if they ask me. Obviously I don't just push my
worldviews on students, but when they ask me about "Web3" what am I supposed to
say? That I hate it? That they shouldn't chase trends? That if that's why they
are interested in computer science, they should just pursue a degree in
economics? Maybe I could save them the heartache that I've experienced. I'm not
sure. I don't know if it's my place. I told the student that the computer
science department doesn't have courses on "Web3" but there may be clubs that
focus on this topic. A student asking me about Web3 is like me asking my grad
Chemistry TA about snake oil and how I can learn more about it. 

== open source
/* - exploitation of open source */

== the real world
Chemistry is grounded in the real (natural) world. Chemists have to deal with
real concerns, like finding drugs to cure diseases. No one told me chemistry
were going to change the world. The problems in chemistry are carved out for
us. On the other hand, the tech people got to dream up their own problems, and
sell them as elaborate and stories of riches and happiness. 

== So much software is shit 

== conclusion
At my jobs in the research sector and the acadamia sector, despite our low pays, we
all stayed because we cared. Meanwhile softwar engineers drop companies like
hot plates at the slightest indication that someone else would offer them
something better. I've got over my allotted ofice horus slot and freed up
weekends to mark exams and projects because I care. Despite lower pay, and no
one telling you that "your work will change the world" I've felt happier than I
ever was in the technology industry. 
