---
title: Universal Chemical Synthesis and Discovery with ‘The Chemputer
---

* closed-loop robotic chemical search engines
* current automation focuses on engineering solutions to practical solutions, not much on "realities of laboratory-based research"
** organic chemist: thinking backwords and forwards => need new abstraction, closed-loop programming => instead of testing reactions with different parameters and conditions, need "development of an approach to universal chemistry using a programming language with automation in combination with machine learning and artificial intelligence (AI)"

* chemometrics:
** unsupervised approach: principal component analysis
** supervised approach: support vector machine, partial least-square discriminant analysis

* combining chemometrics with automation:
** increased productivity (complete automation of complex experiments)
** increased reliability (reduce human error + algorithms which can display results graphically)
** improved safety
** increased efficacy
** valuable time where chemist can focus on research

=== robotics for automation/optimization
* automation so far focusses on a single type of reaction (not universal)
* hardware that is plug-and-play

=== ML towards chemical space exploration
* human vs. robot based discovery: robot more efficient and accurate
* algorithm-based search able to cover 9 times crystalliztion space than random search and 6 times more than human discovery
** curiosity algorithm
* retrosynthetic routes: monte carlo tree search and symbolic AI

=== programmable modular system: the chemputer
* four stages: reaction, workup, isolation, purification
* chempiler: creates low level instructions for hardware
* us ML that can use results of prior experiments to plan future experiments
* autonomous robots need to be able to access novelty/quality of obtained results
** confirm repeatability, if yes, then continue
** does result have precedent => check to see if the observation has been recorded before, if no, otherwise use current knowledge to predict the result, if can be predicted, then result is novel
