---
title: temporal planning and hein lab data-driven feedback
date: 2024-06-27
tags: data-driven
---

== pddl in dynamic environments
- Path-finding in dynamic environments with PDDL-planners
- if adverseries follow deterministic behaviour -> pddl can be used
- mobile robots can use pddl, where environments are modelled by markov decision processes (MDPs)
- re-planning and plan-while aspect
- contingent planning and POMDP planning: serious scalabiltiy issues
- translate partially observable problem to fully observable -> solve by classical planner
- as long as components behaviour is defined by LLFSMs -> can use deterministic planners
- next action
- for data-driven, need a program that calls the planner to generate pDDL on the fly

== random chem and pddl??
- https://easychair.org/publicacations/open/cQB6
- not really related

== temporal planning
=== https://planning.wiki/_citedpapers/pddl212003.pdf[pddl2.1 : An Extension to pddl for Expressing Temporal Planning Domains]
- for temporal + resource-intensive planning domains
- sections: 2 (non-specialist readers), 3 (syntax of numeric expressions/durative actions), 4 (how metrics can be provided), 5 (durative actions as way of modelling temporal properties of planning domain, discrete and continuous actions), 6, 7, 8, 9 (process by which plans were validated), 11 (related work)
- levels of power:
  - 1: STRIPS
  - 2: numeric extensions
  - 3: discrete durative actions
  - 4: continuous durative actions
  - 5: spontaneous / physical processes
- uses of PDDL in competition: https://www.icaps-conference.org/competitions/

==== section 2
- https://www.cs.umd.edu/projects/shop/description.html
- "Syntax checking tools can be used to confirm that the requirements flags are correctly set for a domain and that the types and other features of the language are correctly employed.", where are these tools

==== section 3
- numeric expressions not allowed to be terms (arguments to predicates or values of action parameters) -> numbers do not exist as unique and independent
- numbers only manipulated through relationship with objects that are identigied + named in initial state
- many planning approaches require finite number of action instances -> having numbers as arguments makes the number of instances infinite because numbers do not have finite ranges

==== section 4
- plan metrics, introduced because of the addition of numbers -> specify for planner, basis on which plan will be evaluated for particular problem
  - different plan metrics yield different optimal plans given same initial and goal states
- metric to guide development of solution, might be evaluated post hoc
- total-time: can be used to refer to temporal span of entire plan
- to define a metric with specific quantity, necessary to instrument that quantity in domain
- plan metrics usage is subtle can have dramatic impact on plans: all actions increase a metric to be minimized, or all decrease a metric to be maximised, or some actions decrease and some increase
- case where plans of arbitrarily high utility can be constructed: ill-defined problem, since optimal plan does not exist
- non-trivial to determine whether a planning problem provided with metric is ill-defined -> introducing numeric expressions makes planning problem undecidable, determining if planning problem is well-define is undeciable

==== section 5
- durative action
  - discretized and continuous
  - logical changes are instatantous, but numeric changes are over an in terval
  - annotated condition: make explicit whether condition holds at start of end
  - annotated effect: make explicit if effect is immidiate (start) or delayed (end)
  - invarient condition: holds over entire action
- introducing time -> now can have concurrent plans
  - time is point-based rather than interval-based
- numeric change with discretized durative actions
  - continuous change modelled with durative actions with discrete effects  -> step functions to describe instat change at beginings or ends of durations of actions
    - at start and over all constraints
- durative actions with continuous effects
- planner must have access to values of these continueous quantities at at arbitrary points on time-line of plan, use #t
  - another way to intepret continuous change is as a differntial equation: `(decrease (fuel-level ?p) (* #t (consumption-rate ?p)))` same as d/dt '(fuel-level ?p) = (consumption-rate ?p)'

==== semantics
- assign, increase, scale-up, decrease, scale-down

== data-driven chemistry papers
=== From eyes to cameras: Computer vision for high-throughput liquid-liquid separation
=== A Chemist’s Guide to Multi-Objective Optimization Solvers for Reaction Optimization
- multiple objectives, add weight to each -> single objective -> optimized with single objective optimization methods, but not accurate
- pareto approximation: identify entire set of Pareto solutions in single optimization run
- TSMEO: Thompson Sampling Effective Multi-Objective Optimization
- MVMOO: multi variable optimization
- overview
  - MVMOO: continuous variable, categorial variabile
  - EDBO+: discrete, categorical, batch/parallel
  - dragonfly: continueous, discrete, categorial, batch/paralell, constraints
  - TSEMO: continous, batch/parallel
  - EIM-EGO: continous
- features:
  - continuous variable: temperature, residence time, catalyst/reactant concentration
  - discrete
  - categorical: type of solvent, catalyst, reagent
    - historically under utilized, more focus on continuous variables
    - bayesian approch: preferred method -> create a surrogate model from avalible data (based on gaussian process, inputs are real valued and inherently favors continous variables)
  - discrete vs. categorical: in discrete, order matters
  - handling constraints: due to physical, hardware, safety concerns
    - only dragonfly does, but so far no real application of MOO in reaction optmization that incorporates contraints
- stopped reading pg 11

=== Automated self-optimization, intensification, and scale-up of photocatalysis in flow
- BO: optimize black box reactions
- DoE, statistical modelling can be integrated, but ML is better for non linear (?)
- software:
  - planner - BO, proposes experiments, and then which are automatically executed and analyzed, output is fed back to BO, and new set of conditions are generated
    - every BO campaign: latin hypercube sampling initalization -> optimization toward maximizing objective function happens
  - coordinator: maangeworkflow
  - GUI

=== Delocalized, asynchronous, closed-loop discovery of organic laser emitters
- 2nd gen of AI-guided experimentation: distribution, delocalization
- BO: multioutput GP surrogat emodel trained on spectroscopic data from all completed experiments, used embadding vectors form pretained GNN as molecular featurization

=== An integrated self-optimizing programmable chemical synthesis and reaction engine
- most systems not able to adapt to changing circumstances in real time
- process sensors + analytical instruments coupled with chemputer
- telemetry data: process state monitering + predefined rules -> dynamic procedure execution, self-correction, real-time decision making
- key requirement for any autonomous chemical robot: ability to dynamically execute given list of instructions WITH real time adaptation to changing process parameters
  - hardware/software sensors
  - dynamic xdl
  - software package for analytical instrument control
  - xdl based pacakge for iterative reaction optmization
- results
  - extension of xdl
    - base class for dynamic processes: exposing three abstract methods to control execution flow, each method returns list of steps to be exectued, based on current state of step
    -   set of dynamic xdl steps to allow self-correcting procedure execution for range of potential use cases
    - ChemputationOptimizer software: dynamically update procedure paramtes based no end-point measurement obtained from given analytical instrument
      - cycle repeated maximum number of iterations or until desired target is reached
- methods:
  - chemputer software
    - dynamicStep: run procedure iteratively, updating user-defined paramters using feedback from analytical instruments
      - dynamicAdd, dynamicTransfer, doUntil
    - optmizestep, finalanalysis

- code: https://github.com/croningp/summitserver/, https://github.com/croningp/chemputeroptimizer, https://github.com/croningp/analyticallabware
